### ISSUE TITLE
hyperlinked sources do not link to other packages?

### ISSUE THREAD

**Issue by adamse** [haskell/hackage-server#1046]
For example in [Data.Aeson.KeyMap.singleton][1] `M.singleton` does not link to the containers package source.

[1]: https://hackage.haskell.org/package/aeson-2.0.3.0/docs/src/Data.Aeson.KeyMap.html#singleton

**Comment by gbaz** [comment]
As far as I know, this is simply how hyperlinked source works in haddock itself, not anything specific to hackage server or its builders.

As I recall, only hyperlinking identifiers for the same package was done on purpose, otherwise damn near every single identifier would be a link. As is, I believe hover still gives type information even for things from other packages.

**Comment by adamse** [comment]
I see! Thank you for the info.
