### ISSUE TITLE
Bug: hoogle data is missing parens in function types

### ISSUE THREAD

**Issue by andys8** [haskell/hackage-server#1101]
## Issue

If a function takes a function as argument, parens are critical. The output of `/hoogle-data` seems to be missing functions in type signatures.

## Examples

![image](https://user-images.githubusercontent.com/13085980/179030940-db7adb2d-c5b1-4c4e-b2ba-1855943f915d.png)

is exported as 

```
find :: Foldable t => a -> Bool -> t a -> Maybe a
```
![image](https://user-images.githubusercontent.com/13085980/179031002-f5a760ab-370c-4422-a991-8c1273714abd.png)

or `filter`

![image](https://user-images.githubusercontent.com/13085980/179031124-cba770a0-b3c5-445d-9fd5-0597fdaf02b0.png)

```
filter :: () => a -> Bool -> [a] -> [a]
```

![image](https://user-images.githubusercontent.com/13085980/179031081-f5024250-bff9-4ae8-90dc-b08700751ae0.png)

## How to reproduce the issue

* Download data from https://hackage.haskell.org/packages/hoogle.tar.gz (documented in https://hackage.haskell.org/api#hoogle-data)
* Open `Prelude/0.1.0.1/doc/html/Prelude.txt`
* Jump to line 2438 or search for `filter`

You'll find `filter :: () => a -> Bool -> [a] -> [a]`
(with missing parens around `a -> Bool`).

**Comment by gbaz** [comment]
I suspect this is an underlying issue with haddock, which is called to produce the --for-hoogle output?

**Comment by andys8** [comment]
How can the bug be boiled down? What is the reason it doesn't affect other tools?

E.g. `hoogle` cli isn't affected

![image](https://user-images.githubusercontent.com/13085980/179218654-a007df3a-9a4a-4771-b912-95ce95c6df76.png)

Although it seems to be downloading `packages/hoogle.tar.gz`.

![image](https://user-images.githubusercontent.com/13085980/179218811-a59a523b-5866-43c5-a9a7-a94ad7b2b814.png)

Although I see the generation and caching I've trouble to figure out how docs are currently **actually*
 generated. Could you point me to where you suspect the issue to happen?

**Comment by gbaz** [comment]
So you're looking at an old version of an old package. you can see its generated hoogle info here: https://hackage.haskell.org/package/Prelude-0.1.0.1/docs/Prelude.txt

Indeed it is missing parens. This was due to however hoogle or haddock generated that info at the time that old package was built (five years ago). (cf https://hackage.haskell.org/package/Prelude)

For reference, how this stuff is built is the build client calling cabal with the haddock and hoogle flags: https://github.com/haskell/hackage-server/blob/b4ea1c73ba85f24985259fd1df4664747ceb0159/exes/BuildClient.hs#L735

But that said, I think this was an old issue on older haddock, but there just so happen to be some older packages which were generated when that issue pertained.

The hoogle db generated for a current version of base, for example, and by contrast, has the expected parens: https://hackage.haskell.org/package/base-4.16.2.0/docs/base.txt

On this basis, I'm going to close.

**Comment by andys8** [comment]
> But that said, I think this was an old issue on older haddock, but there just so happen to be some older packages which were generated when that issue pertained.

I assume updating legacy documentation is out of scope.

Interesting, thanks for digging into the issue :)
