### ISSUE TITLE
Downloads statistics is not working for several packages

### ISSUE THREAD

**Issue by Oleksandr-Zhabenko** [haskell/hackage-server#1258]
I have noticed earlier that the number of downloads usually is updated every day once a day (usually at night in my local time). I downloaded using `cabal get phladiprelio-ukrainian-simple` on Sunday once and on Monday morning did not see the changes in number of both total and monthly downloads on the page
[https://hackage.haskell.org/package/phladiprelio-ukrainian-simple](https://hackage.haskell.org/package/phladiprelio-ukrainian-simple)

On Monday I tested four packages for downloads statistics changes, downloading using `cabal v1-install --reinstall <package-name>`:

- phladiprelio-ukrainian-simple
- phladiprelio-general-simple
- phladiprelio-general-datatype
- rhythmic-sequences

On Tuesday morning there are no updates in their downloads statistics at all.

Are there any changes in its work or is it related to something else?

Will it be updated in the nearest future?

**Comment by gbaz** [comment]
installing packages won't cause packages to redownload. they'll be cached on your system. also note package downloads are already very partial because even if the download occurs, it will need to cause a cache miss in our CDN for it to register as a download on hackage -- we have a ticket about that somewhere.
