### ISSUE TITLE
Maintainers are being 403'd when they try to upload a package

### ISSUE THREAD

**Issue by bitemyapp** [haskell/hackage-server#235]
Upload privs are part of the privs of being a maintainer on a package.

```
Uploading dist/bloodhound-0.1.0.2.tar.gz...
Error: dist/bloodhound-0.1.0.2.tar.gz: 403 Forbidden
Error: Forbidden

No access for this resource.
```

^^ I get the same thing in the browser. I'm listed as a maintainer.

I log in successfully, can edit package information, just can't upload. I was able to upload packages before.

**Comment by jdnavarro** [comment]
I can upload packages only as *package candidates* and then publish them manually. I sometimes get a 503 in the browser when doing so, but then I can see the package has been published.

Since this can become quite cumbersome when you have to make frequent releases, what's the work-around do you recommend as of today? Create another user account? Request whitelisting from *Package uploaders*? Can this be avoided somehow by using `curl` directly?

**Comment by dcoutts** [comment]
It sounds like for some reason your account is not in the uploaders group. Email the hackage admins and ask them to fix it. Or find us on #hackage IRC and ask.

**Comment by jdnavarro** [comment]
It turns out, that for some reason, I wasn't in the package uploaders group. @dcoutts added me to the group and now I don't have this issue anymore.

**Comment by mantkiew** [comment]
same for me today. I uploaded a new version successfully on March 6 but couldn't upload today. I am in maintainers group for the package.

**Comment by LukeHoersten** [comment]
Is there a fix for this yet? I'm still having the problem.

**Comment by mantkiew** [comment]
You need to be added to the uploaders group. As for the explanation, quoting Duncan:

"[...] we originally required a manual
verification step for joining the uploaders group. What we hadn't
realised, but you discovered was that there was a side route to
uploading anyway, via the candidates method. I recently closed that
loophole, which is why you saw it stop working. [...] we now put
everyone into the uploaders group automatically for new users, but some
people registered in that window."

**Comment by LukeHoersten** [comment]
Thanks. I got in contact with him. I can't believe how much nicer this new process is.

**Comment by IvanMalison** [comment]
I created my account very recently, and I'm still running in to this issue.

**Comment by tfausak** [comment]
That may be intentional. New accounts must send an email to the Hackage admins before they are allowed to upload a package. [The account registration page](https://hackage.haskell.org/users/register-request) says:

>  After your account is created, you cannot upload until you contact the hackage admins at admin@hackage.haskell.org and send an email requesting to be added to the uploader group. (This measure is unfortunately necessary to prevent spam accounts). 

See this issue and the linked threads for details: https://github.com/haskell/hackage-server/issues/685#issuecomment-367867604
