### ISSUE TITLE
Include tarball hash in packages tarball

### ISSUE THREAD

**Issue by shlevy** [haskell/hackage-server#309]
It would be useful if the `00-packages.tar` file included package tarball hashes, perhaps in some `x-tarball-sha256` field. This would in general allow tools to verify the integrity of packages downloaded from hackage, and in particular for my interests would make it so the [hackage2nix](https://github.com/NixOS/cabal2nix) tool could package hackage in [nixpkgs](https://github.com/NixOS/nixpkgs) without having to download all of the tarballs to the local machine (nix requires a hash to be known in advance for builds that do impure things like networking).

I'm not exactly sure how the packages tarball is created, but I imagine this could be calculated at the time a new package is uploaded. If something along these lines would be acceptable, let me know and I'll start diving into the code to open up a PR.

**Comment by shlevy** [comment]
cc @peti

**Comment by peti** [comment]
Yes, that would be a great feature! :+1: I'm sure all distributions could benefit from having the hash of the tarball included in the distributed Cabal file. Right now, the only way to get that hash is to download the tarball, so technically speaking having a Hackage API that serves just the hash (instead of the whole file) would be an improvement already. Amazon S3 includes the contents hash in the response to an HTTP HEAD request, for example. Anyway, having the checksum in cabal-install's `00-index.tar` file would certainly be the most convenient solution for us at NixOS.

**Comment by hvr** [comment]
Can't the ETag be used for that purpose?

**Comment by shlevy** [comment]
A sha would be preferable, and as @peti says it would be nicer for our particular needs if it was included in the index tarball, but this does get us a significant portion of the way!

**Comment by dcoutts** [comment]
This is in the works as part of signing the package index.

**Comment by shlevy** [comment]
Cool! Anything we can help with?

**Comment by dcoutts** [comment]
@thoughtpolice and I will publish our design on the well-typed blog soon. That'll explain things and would be a good starting point if you'd like to help us.

**Comment by hvr** [comment]
Fwiw, the new `01-index` tarball  contains sha256 checksums. So I'd consider this issue resolved. Please reopen if not.
