### ISSUE TITLE
Prevent uploads over insecure HTTP with basic authentication

### ISSUE THREAD

**Issue by snoyberg** [haskell/hackage-server#348]
There have been two separate discussions on this proceeding so far:
- https://github.com/haskell/cabal/issues/2561
- https://mail.haskell.org/pipermail/cabal-devel/2015-April/010124.html

The issue is that cabal-install (until yesterday's commits to master) uploads to Hackage over an insecure connection with basic auth, which reveals the user's username and password in base64-encoded plaintext to anyone viewing the packets. The main problem should be fixed in cabal-install, but there's a Hackage aspect to this as well.

My proposal: Hackage should refuse uploads that come over unsecured HTTP connections. There are plenty of other options as well, but I recommend we make a decision quickly due to the severity of the security hole here.

**Comment by hvr** [comment]
Afaik, I think implementing `digest-auth` in cabal-install and refusing basic-auth over non-TLS (after all, it's not being advertised anyway) should be doable rather quickly

**Comment by drbo** [comment]
No, this is not a valid solution.

An attacker can launch a silent MITM attack on any insecure connection.  `cabal-install` should _never_ use insecure connections.  Ever.  Neither should hackage.

**Comment by hvr** [comment]
@drbo I don't consider TLS secure enough either, since we don't have end-to-end security due to the CDN "MitM" reverse proxy between Hackage and cabal clients.

See also http://www.well-typed.com/blog/2015/08/hackage-security-beta/  which in phase 1 addresses ensuring that packages are authentic and allowing to finally have a proper Hackage mirroring infrastructure.

Later phases would be able to address authenticating package uploads to Hackage over plain unencrypted HTTP connections, as TLS would be non-essential (but still useful as an additional although somewhat ineffective protection).

**Comment by gbaz** [comment]
This was resolved some years ago (as evinced by the above link) but the issue was never closed. Tidying now.
