### ISSUE TITLE
Description field not rendered correctly

### ISSUE THREAD

**Issue by nad** [haskell/hackage-server#349]
If I run `cabal haddock` locally for the package ChasingBottoms (using GHC 7.8.3/7.8.4/7.10.1, and corresponding versions of Haddock), then the description field is rendered correctly, but not on Hackage:
- https://hackage.haskell.org/package/ChasingBottoms-1.3.0.11
- https://hackage.haskell.org/package/ChasingBottoms-1.3.0.12

Is Hackage using a different semantics for the description field?

**Comment by dcoutts** [comment]
It's using an older version of the haddock syntax. We should move to using the haddock library directly, or the pandoc lib.

**Comment by eightyeight** [comment]
Would be lovely if this were fixed. Is it something a complete noob could do?

**Comment by nad** [comment]
> In the meantime, don't use >> or >>>

I followed this suggestion, but the description field is still rendered incorrectly:

* https://hackage.haskell.org/package/ChasingBottoms-1.3.0.13

**Comment by dcoutts** [comment]
@eightyeight yeah probably. There's a couple approaches now: use the haddock lib directly, or update the existing lexer+happy parser, or switch to using pandoc for the haddock parsing.

**Comment by dcoutts** [comment]
@nad I'm not sure which bit of new markup you're using, but what I'd recommend now is to have your description be just a couple paragraphs, and then put the rest of it in the README.md which will be rendered at the bottom of the page.

**Comment by eightyeight** [comment]
@dcoutts the readme approach is the one I've taken. It has the benefit of being visible on GitHub as well.

**Comment by thormick** [comment]
I'm having the same issue with my package http://hackage.haskell.org/package/HaskRel-0.1.0.0

To me it looks like the description is just dumped out as raw text, I don't see any markup that has been processed, even markup that is the same as other packages on Hackage. (Looking at https://hackage.haskell.org/package/lens and https://hackage.haskell.org/package/lens-4.13/lens.cabal for instance.)

It's not a major issue as I might move more of it into README.md as suggested, it does contain some information that would perhaps belong there, or even on a blog. It's still a nuisance, since I took care to make sure it looked okay when I did `cabal haddock`, so it was a let down that it came out as unformatted text.

I used the package candidate facility to upload, in case that has any significance.
