### ISSUE TITLE
Wrong preprocessor flag for Documentation generation?

### ISSUE THREAD

**Issue by SJost** [haskell/hackage-server#369]
The generated documentation implies that the abstract Datatype `Data.Map.Map` seemingly exports its internal constructors. The source code linked for `Data.Map.Lazy` links to the following, after clicking on source is:
```
    module Data.Map.Base (
      -- * Map type
      Map(..)       
```
However, the actual code enclosed with GHC looks like 
```
    module Data.Map.Lazy (
        #if !defined(TESTING)
          Map    
        #else
          Map(..)
       #endif 
```
My students learning Haskell found this highly confusing, when I gave `Data.Map.Map` as an example for an abstract datatype in Haskell.

**Comment by lfairy** [comment]
I think this is intended behavior. The `Map` type is exported in `Data.Map.Lazy`, but it is defined in `Data.Map.Base`. Since we often use the "source" link to check the implementation of a type, it makes sense for it to link directly to the definition. That has nothing to do with the preprocessor; it's how re-exporting in Haskell works.

Either way, I think it'd be best to bring this up with the maintainer of Haddock (@Fuuzetsu?), not here. We just run Haddock and host whatever it spits out.

**Comment by Fuuzetsu** [comment]
No idea why this would happen, there are plenty of source files (generated by hscolour) on Hackage with include the CPP. There were some changes to cabal to make sure stuff doesn't get double preprocessed due to some clang issues but I don't know if that would change anything.

If you have a small testcase (no `cabal` invocation) then I invite you to the haddock issue tracker and we might be able to resolve it.

**Comment by SJost** [comment]
Okay, thanks for the information!
