### ISSUE TITLE
How can I skip a package when I used hackage-mirror

### ISSUE THREAD

**Issue by Qinka** [haskell/hackage-server#415]
When I mirrored from hackage.haskell.org , a package(s) , named acme-everything , can't be upload to my hackage-server. So I want to ignore this package(s) and continually mirror another packages. But HOW TO ?

**Comment by dcoutts** [comment]
This ought to be handled automatically by the mirroring tool. It does keep a list of packages it cannot mirror and does not keep retrying. So if that's not working here then the logic for deciding what goes into that set needs to be adjusted.

If someone wants to look into this it should not be hard.

**Comment by TomLippincott** [comment]
Not sure if this is related, but it seems in the same space, but using a configuration file like this:

```
source "hackage"
  uri: http://hackage.haskell.org
  type: secure

target "mirror"
  uri: file:/runtime/temp
  type: local

  post-mirror-hook: "echo done"
```

and the command:

```
time hackage-mirror servers.cfg --keep-going
```

it runs for about 30 minutes until it hits a  particular package ("hermes-1.3.4.3") and exits with:

```
mirroring hermes-1.3.4.3
hackage-mirror: Failed to download package hermes-1.3.4.3,
  Unexpected response (5,0,0)for http://hackage.haskell.orgpackage/hermes-1.3.4.3.tar.gz
```

I've tried various combinations of the "type" values (e.g. running my own Hackage clone and using "hackage2" and "secure" as the destinations, etc) but I always seem to end up with either a partial mirror (~4k packages, when there are ~11k on hackage), or an error like the one above.  Also, and maybe this is just due to the unexpected error interruption, it seems to always start over from the beginning and redownload what it already has.

And one final note: the Docker image, after it's build, has a db lock file that prevents firing it up:

```
docker run --rm -p 8080 hackage
hackage-server: Guessing public URI as http://9165ab665a78:8080
(you can override with the --base-uri= flag)
state/db/Tags/Alias/open.lock: Locked by 7: resource busy
```

Not hard to work around, just thought I'd mention it in the spirit of Docker images being plug-and-play.

**Comment by Qinka** [comment]
I forgot to close this issue. Sorry. I gave up to do that, because I didn't have time, and money. At the same time, the friends from Tsinghua University they build a mirror of both hackage and stackage.

Two years ago, I use a cheap computer try to mirror it. That might be the reason. 

So, I think this issue can be closed.
