### ISSUE TITLE
Relative links in Markdown

### ISSUE THREAD

**Issue by Rufflewind** [haskell/hackage-server#427]
Relative links such as

```
See the [license](LICENSE) for more info.
```

are rendered naively on Hackage, which means it will point to the nonexistent URL

```
http://hackage.haskell.org/package/LICENSE
```

It should instead point to

```
http://hackage.haskell.org/package/<pkg>/src/LICENSE
```

(This feature is implemented on GitHub, Bitbucket, GitLab, etc.)

**Comment by ntc2** [comment]
This issue is still present on hackage.haskell.org. So, if the version of Hackage running on hackage.haskell.org right now is using the merged fix, then this issue should be reopened.

For example, this HTML is taken from the rendered README in the [hint package](https://hackage.haskell.org/package/hint-0.6.0):
```html
<p>Check <a href="examples/example.hs">example.hs</a> to see a simple but
comprehensive example (it must be run from the <code>examples</code> directory).</p>
```

Related discussion: https://github.com/mvdan/hint/pull/30.

**Comment by hvr** [comment]
Unfortunately this will break a couple of markdown files which adapted to the status quo... but well
