### ISSUE TITLE
Hackage search "compiler" misses purescript

### ISSUE THREAD

**Issue by 0joshuaolson1** [haskell/hackage-server#474]
The "purescript" package has the word "Compiler" in its name, yet searching with neither the uppercase nor the lowercase word returns it among the results.

**Comment by gbaz** [comment]
nice bug, searching for the word 'Compile' does seem to work. Perhaps an issue with the stemmer?

**Comment by mpickering** [comment]
So the issue here from what I can work out is that a lot of packages mention the word "compiler" in the synopsis and description. This gets stemmed to "compil" so when `pruneRelevantResults` considers which search terms to include (from either `["compiler", "compil"]`) it includes `compiler` as there are only 7 packages which include that term but there are more than 400 packages which include "compil" so this term isn't included. Maybe increasing the hard limit wouldn't be too bad but I can't really comment about the impact.

**Comment by gbaz** [comment]
Doubling the soft and hard limit both I guess, as the limits should probably scale a bit with the overall size of hackage.
