### ISSUE TITLE
manual documentation uploads are not documented

### ISSUE THREAD

**Issue by RossPaterson** [haskell/hackage-server#56]
I understand that maintainers can upload docs if the builder can't build them, via

http://beta.hackage.haskell.org/api#documentation-core

but several points aren't documented:
- The flags that should be given to cabal to get the links right.
- The directory that needs to be tarred.
- How the tar file should be uploaded.

**Comment by liyang** [comment]
I did a release of [`true-name`](http://hackage.haskell.org/package/true-name-0.0.0.1), but forgot to update some documentation, which I fixed in a [post-release commit](/liyang/true-name/commit/e4f971622dd09bbd357c3eef318ed6c212eec1d8). Not wanting to make another release just to fix the documentation on Hackage, I tried to re-upload the docs manually.

The weird thing is: I'm still seeing the [old version of the module documentation](http://hackage.haskell.org/package/true-name-0.0.0.1/docs/Unsafe-TrueName.html), but clicking on the [`Source` link](http://hackage.haskell.org/package/true-name-0.0.0.1/docs/src/Unsafe-TrueName.html#trueName) shows the updated comments. I've checked the `…-docs.tar.gz` I'm uploading and it definitely contains the new `Unsafe-TrueName.html`. I even tried deleting the existing docs via the maintenance pages and uploading my version before it has a chance to rebuild, but to no avail.

Can anyone help me understand what's going on?

**Comment by bitemyapp** [comment]
@liyang I'd just use http://hackage.haskell.org/package/neil to upload the docs.

Documented here: http://neilmitchell.blogspot.com/2014/10/fixing-haddock-docs-on-hackage.html

**Comment by liyang** [comment]
@bitemyapp Didn't know about @ndmitchell's eponymous tool… I was using my own Bash script to do the same.

Have just tried `neil`, and it seems to have done exactly the same thing—still the old module page, but updated (colourised) source.

I'm wondering if somewhere the old version is being cached somehow?

**Comment by bitemyapp** [comment]
@liyang if it was getting cached, I think that would be from the CDN, but it's extremely likely I'm wrong about that. The actual hackage page gets rendered directly from current docs tarball IIRC.

**Comment by sapek** [comment]
Is it still necessary to manually build/upload documentation? I've uploaded a new package [bond](https://hackage.haskell.org/package/bond-0.4.0.1) and it appears that the build never ran. Is this a problem on the hackage side or something I'm doing wrong (it's my first package so quite likely)?

**Comment by lfairy** [comment]
@sapek Have you already uploaded documentation for that package? The builder won't try to build a package if it already has docs.

**Comment by sapek** [comment]
Yes, today in the afternoon I have given up and uploaded docs manually using `neil` to mentioned above.  But I waited almost 24 hours after publishing.

**Comment by cartazio** [comment]
There was some Haskell infrastructure related migrations a week or so ago,
has anyone checked on the health of the build queue?
Likewise, does the test upload facility interact with the build queue?

**Comment by gbaz** [comment]
#553 should resolve this..

**Comment by gbaz** [comment]
since that's merged, closing this out.
