### ISSUE TITLE
Additional "Latest upload date" column in search results

### ISSUE THREAD

**Issue by ocramz** [haskell/hackage-server#618]
I think it would be extremely useful to sort by most recent upload, to quickly have a sense of livelihood of a dependency before importing it into a project.

I could add this feature myself if someone knowledgeable tells me where to look. Thanks!

**Comment by hvr** [comment]
Tbh, I think that can easily be a misleading metric, as it depends on the maintainer's style (some release early and often w/o much hesitation, while other act more prudently and have more principled development cycles). What kind of information do you infer from a package whose last upload dates back say over a year ago? Wouldn't a metric which tells you how reliable its CI status had been over the last 12 months be more relevant, or one which tells you how many reverse dependencies a package has?  I'm also slightly hesitant, because we have a limited budget of horizontal width available currently (unless we redesign the UI to allow for e.g. collapsible columns), and we need space for at least one or two columns for features that aren't enabled yet.

**Comment by gbaz** [comment]
I think it's a useful data point, as one among many. If it hasn't been
uploaded since say 2009, that's worth noting for example :-)

We could do date format compactly if we work at it...

**Comment by lwm** [comment]
I'm not sure if this is the right place but I recently saw that the last upload date is gone from the package search url (`http://hackage.haskell.org/packages/search?terms=<package>`) and pretty much the only field I ever need there is last upload date (helps when maintaining on stackage). I'd appreciate to see it again for sure!

**Comment by gbaz** [comment]
Yep, this is the right place. I'll cook up a patch to add it back soon.

**Comment by ocramz** [comment]
@hvr indeed, CI status is a good metric of livelihood, provided all packages implement it (which is far from established practice esp. for older ones).
Reverse dependency count is also a good metric, @gbaz at ICFP mentioned it's a planned feature which makes me happy.
I just thought release date is a good _proxy_ for repo livelihood, and I find myself subconsciously looking for it when including new dependencies.

**Comment by hvr** [comment]
As long as the release date is just one more sortable column but doesn't enter the search-scoring I'm ok with it. However, I'm curious how that information helps @lwm during maintainance. 

As for the CI status; Indeed, it wouldn't work if packages needed to actively implement it. I'm talking about a different kind of CI quality metric (an idea inspired by something I was told Google supposedly does internally) which deliberately doesn't involve packages actively supporting it.
