### ISSUE TITLE
hledger-1.5 appears to be missing from index tarball

### ISSUE THREAD

**Issue by peti** [haskell/hackage-server#651]
We have https://hackage.haskell.org/package/hledger-1.5, but cabal doesn't seem to know about it:

~~~
$ cabal update && cabal get hledger
Downloading the latest package list from hackage.haskell.org
Unpacking to hledger-1.4/
~~~

Cc: @simonmichael

**Comment by simonmichael** [comment]
It worked for me just now, with cabal 1.24 and cabal 2.0.0.0..

**Comment by peti** [comment]
Wiping the current state of ~/.cabal/packages/hackage.haskell.org seems to make a difference. Not sure what is going on. I was using a development version of `cabal-install`, and it's possible that my database state got confused in some unique way. The error shown above occurred with the latest release version, too, though.

**Comment by gbaz** [comment]
This may be a rather more widespread problem, ugh. Thanks for the heads up. We're investigating.

**Comment by gbaz** [comment]
This was due to an interaction between cabal and the revised tarball. Can be resolved by clearing out the index files and running `cabal update` again as per: https://mail.haskell.org/pipermail/haskell-cafe/2018-January/128385.html

The underlying issue will be resolved by: https://github.com/haskell/hackage-security/pull/198
