### ISSUE TITLE
Can't authenticate in Firefox or Chrome on Windows

### ISSUE THREAD

**Issue by sjakobi** [haskell/hackage-server#671]
I tried to upload a package but was repelled each time by the authentication dialogue no matter whether I used Firefox or Chrome. After I submitted my username and password the authentication simply reappears empty without any indication of what went wrong.

I had no problems using Chromium on Linux or when uploading via the API using Windows.

My password is 70 ASCII chars – not sure if that's part of the problem.

**Comment by gbaz** [comment]
Is there by chance a firewall involved in the windows browser situation?

**Comment by sjakobi** [comment]
> Is there by chance a firewall involved in the windows browser situation?

Not that I'm aware of. It's a standard Windows 10 Home edition in the same environment as the Linux machine.

**Comment by gbaz** [comment]
I googled around and couldn't come up with any digest-auth bugs that might relate. However, if you're interested in digging in, I did find that in chrome developer tools I could go to a page requiring auth and look at the request headers to see e.g.:

>  Authorization:Digest username="XXX", realm="Hackage", nonce="XXX", uri="/package/HList/maintain", response="XXX", qop=auth, nc=00000004, cnonce="XXX"

(It took me a couple reloads to see this for some reason).

It may be the case that something of interest can be found by comparing how this looks in the windows and linux versions of chrome. 

But since you are using chrome in both situations, it is hard for me to imagine why things would only be going wrong in one case, unless there is indeed some weird proxying or something built directly into the windows box.

Sorry I can't be of more help here.

**Comment by gbaz** [comment]
One additional thought -- it may be that the difference is in the underlying (sqlite?) db in which these browsers store and retrieve the password. There may be platform-specific quirks in this regard -- and checking your saved passwords in chrome settings may be informative here.

**Comment by sjakobi** [comment]
Thanks a lot for your suggestions @gbaz! I'm afraid I can't reproduce the issue any more. In case it reappears I'll know how to investigate it thoroughly! :)
