### ISSUE TITLE
Unknown compiler name 'eta'

### ISSUE THREAD

**Issue by cblp** [haskell/hackage-server#674]
Source:
```
...
library
    hs-source-dirs: lib
    if impl(eta)
        hs-source-dirs: lib-eta
    else
        hs-source-dirs: lib-ghc
...
```
(https://github.com/cblp/crdt/blob/v9.2/crdt/crdt.cabal)

Perfectly selects between Eta and common GHC compiler locally.

But when I try to upload it to Hackage, I get
```
Error: Invalid package

Unknown compiler name 'eta', 'eta'
Control.Exception.Safe.throwString called with:

Upload failed on crdt-9.2.tar.gz
Called from:
  throwString (src/Stack/Upload.hs:195:17 in stack-1.6.3-J1I753MGXoT93WwgNHFXcA:Stack.Upload)
```

Why cannot I use different compilers?

**Comment by 23Skidoo** [comment]
There's no support for Eta in the upstream Cabal library, so if this works with Eta tooling, I suppose that they use a fork or their own implementation.

**Comment by cblp** [comment]
You are partly correct. No special support is needed to evaluate `impl(eta)` to False, and the upstream Cabal already does this.

**Comment by cblp** [comment]
If this works with Eta tooling, it's Eta's issue. I'm drawing your attention to the fact it works with upstream GHC and Cabal, but not Hackage

**Comment by 23Skidoo** [comment]
Then I believe the issue will be automatically resolved once Cabal 2.2 is released and `hackage-server` is upgraded to that version.

**Comment by cblp** [comment]
I don't think so. The problem is not in the presence or lacking support. My local `cabal check` says

```
The following errors will cause portability problems on other environments:
* Unknown compiler name 'eta', 'eta'

Hackage would reject this package.
```

too.

So the problem is in rejecting packages supporting "non-supported" compilers.

**Comment by cblp** [comment]
Support of GHC mustn't imply unsupport for others.

**Comment by 23Skidoo** [comment]
If `cabal check` rejects it, then it still should be fixed in lib:Cabal.

**Comment by gbaz** [comment]
In general, I don't understand the `eta` story for cabal integration (or lack thereof). I think it would be necessary to consult with their devs as to their plans and how they intend to integrate with cabal. It doesn't make a ton of sense to allow `cabal check` to understand `eta` imho, if it doesn't have any related tooling that actually allows cabal to build with `eta`.

It might make sense to just allow `eta` past the check as a stopgap. But I would think the real question is how much the https://github.com/typelead/etlas tool diverges from cabal (it looks to be built over a fork) and to what extent we could upstream at least _some_ of the changes...

**Comment by gbaz** [comment]
Relatedly, my understanding as per: https://blog.eta-lang.org/eta-in-practice-working-with-haskell-packages-5dfa3dc0c98a is that the recommended way to produce packages is to _just_ put the ghc-compat package on hackage, and to put the eta-specific changes in their overlay... If that isn't the case anymore, then it would be good to get some clarity?

**Comment by 23Skidoo** [comment]
Right, it'd be nice if someone from the Eta team could comment.

**Comment by hvr** [comment]
I should reach out to @rahulmutt again; when Eta started out I started thinking about how to cope with extending hackage in order to be able to facilitate/improve support for multiple platforms (ghcjs and eta, and soon maybe ghc/wasm), which all come with different enough requirements in terms of FFI, as well as make it easier for packages to provide "portable" FFI-less pure-Haskell configurations. But when Eta started exploring the design-space via Etlas and by using out-of-hackage patching, the pressure to address this faded, and I stopped pursuing this. If Hackage however is going to start hosting Eta packages, we should figure out a proper scheme to properly accomodate support in the metadata. We should tackle this over the next couple months (and rush to any quick action w/o first considering the big picture)

**Comment by cblp** [comment]
By the way, I don't consider my package an Eta package, it's a Haskell package, just with a few platform-specific lines.

**Comment by rahulmutt** [comment]
Etlas is really only there so we can add in some features that are specific to Eta that don't make sense inside of Cabal:
- Be able to add dependencies to JVM libraries
- Include Java sources to your project
- Transparently handle patches from `eta-hackage`
- And a few others

The plan is to keep syncing with new versions of `Cabal` and `cabal-install` as necessary and adopt some of the new features (like `new-build`, Backpack, etc.).

The plan for packages is to eventually submit PRs upstream in a manner similar to what @cblp has done: the Eta-specific files will be included using the `impl(eta)` Cabal conditional for all packages that intend to be compatible with both Haskell and Eta. We have already submitted a couple of PRs which were just 1 line changes that push the compat changes upstream so that we don't have to maintain patches for those packages for future versions.

We intend to do the same for all the other packages/patches as well. We are just waiting until 100% of the tests of the respective package have passed before submitting a PR. So once this process is over, we hope to get rid of `eta-hackage` altogether, but it will definitely take some time to get there.

How do we distinguish between an "Eta" package and a "Haskell" package? An Eta package is a package that is intended to be used with Eta *only* and not with Haskell - say it's purely function wrapper of a popular Java library. We have made it clear to our community that such packages should *not* be uploaded to Hackage.

Hopes that clears things up! Feel free to tag me on any Eta-related matters.

**Comment by hvr** [comment]
@rahulmutt the only trouble I have with this is that I don't like the `impl(eta)` pattern, which I already consider an anti-pattern as far as `impl(ghcjs)` and `impl(ghc)` are concerned (where we added some rather weird semantics as a hack). We should rather try to figure out a more declarative scheme that tries to describe features rather than versions. One scheme I was originally working on (I don't remember if I mentioned that one to you in 2016), was about formalising Eta's FFI extension under a specific token name, and use a similiar scheme like we do for declaring a requirement of TemplateHaskell via `other-extensions` (or a predicate which I intended to implement in cabal but didn't get to yet, which could use in place of `impl()`). That way we avoid this non-scalable "if compiler-x then, elif compiler-y then", etc, but rather we abstract over "if compiler-has-property-x then, elif compiler-has-property-z then, ..." which is much more elegant.

**Comment by rahulmutt** [comment]
@hvr That mechanism is elegant indeed, +1. Keep me posted on how that progresses.

**Comment by cblp** [comment]
Something like `if os(jvm)` or `if arch(jvm)`?

**Comment by hvr** [comment]
@cblp not quite; that doesn't address declaring which language extensions/syntax the compiler ought to support. E.g. if it supports `{-# LANGUAGE TempalteHaskell #-}` or if it supports `{-# LANGUAGE CApiFFI #-}` or `{-# LANGUAGE JavaFFI #-}` (i.e. the whole point of having a modularised language with tokens for identifying each extension is so we can standardise extensions, enable/disable them,  and declare a dependency on them).

**Comment by 23Skidoo** [comment]
> Etlas is really only there so we can add in some features that are specific to Eta that don't make sense inside of Cabal:
>
>    Be able to add dependencies to JVM libraries
>    Include Java sources to your project

I should mention that when we added support for GHCJS, we also added support for including JavaScript sources in Cabal packages (the `js-sources` field), so this bit actually makes sense inside Cabal. I think a special field for specifying JVM deps would make sense as well, analogously to how we have `pkg-config-depends` and macOS-specific `frameworks`.

**Comment by hvr** [comment]
> Cabal should simply parse these as "known" fields but should not restrict the format of the values of those fields (essentially it should allow any sequence of characters).

I don't like that tbh; we're in the process of cleaning up cabal's formal syntax and fully specify its grammar as much as possible; what you're asking us is to deliberately leave holes in it.

**Comment by 23Skidoo** [comment]
+1 to what @hvr said, it'd be better to have proper types and grammar specifications for the stuff that goes into those fields (e.g. a `MavenDependency` and a `MavenRepo` type for `maven-depends` and `maven-repositories`), even if those data types will be initially unused by the Cabal library.

**Comment by rahulmutt** [comment]
@hvr @23Skidoo Sure that's fine. What should be the ideal place to define `MavenDependency` and `MavenRepo`?

**Comment by hvr** [comment]
@rahulmutt you could follow the precedent set by

- http://hackage.haskell.org/package/Cabal-2.0.1.1/docs/Distribution-Types-PkgconfigDependency.html

i.e. create modules in the `Distribution.Types.*` hierarchy

**Comment by rahulmutt** [comment]
Sure. I'll file an issue on the Cabal repo when I get time.
