### ISSUE TITLE
Candidate package not found in link from list of maintained packages

### ISSUE THREAD

**Issue by philderbeast** [haskell/hackage-server#764]
If I upload a package candidate for `siggy-chardust`, when this package is not yet on hackage, it uploads and I arrive at its readme.

http://hackage.haskell.org/package/siggy-chardust-1.0.0/candidate#readme

From there I can follow the following link trail.

http://hackage.haskell.org/package/siggy-chardust-1.0.0/candidate/maintain
http://hackage.haskell.org/package/siggy-chardust/maintainers/
http://hackage.haskell.org/user/philderbeast

This last page lists packages I can maintain. I have one package uploaded to hackage, `flight-igc`. The link to that is good but links to packages that so far have only been uploaded as package candidates are broken, such as the following that shows **package not found**.

http://hackage.haskell.org/package/siggy-chardust

**Comment by hvr** [comment]
This is because, technically, that package doesn't "exist" yet; as long as a package is merely in the candidate index but not the primary index, it's treated as if it doesn't fully exist yet. We need at least one non-candidate version before we can materialise the non-candidate package-view. We could show some "this package hasn't been published yet, but there's candidates available here" place-holder page -- that'd require some serious special casing in the rendering logic (& templating).

**Comment by gbaz** [comment]
Candidate links are now listed alongside normal links in user pages now, thanks to gsoc work.
