### ISSUE TITLE
Uploading packages with the "publish" option results in 404

### ISSUE THREAD

**Issue by nikita-volkov** [haskell/hackage-server#772]
Since some time very recently I'm unable to upload any package like this. E.g., it results in the following error:

```bash
$ cabal upload --publish dist/potoki-core-2.1.0.1.tar.gz 
Hackage username: NikitaVolkov
Hackage password: 
Uploading dist/potoki-core-2.1.0.1.tar.gz...
Error uploading dist/potoki-core-2.1.0.1.tar.gz: http code 404
Error: Page not found

Sorry, it's just not here.
```

Uploading without the `--publish` option, goes fine.

JIC, my Cabal is:

```
$ cabal --version
cabal-install version 2.2.0.0
compiled using version 2.2.0.0 of the Cabal library
```

**Comment by gwils** [comment]
My coworker hit this yesterday. If you run `cabal --http-transport=wget upload blah` with `wget` on the path, I believe that should work.

**Comment by gbaz** [comment]
@nikita-volkov can you paste the output of `curl --version` into this ticket?

**Comment by pikajude** [comment]
```
~ $ curl --version
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy
```

**Comment by gbaz** [comment]
We traced this down and figured out it was introduced by this change:

https://github.com/haskell/hackage-server/commit/f8e0060aa150a50852e1efd9e20faa9a2d8d4125#diff-568cf93f124db57828a18cc702b29cf4L311

This broke curl's digest-auth but not wget's, oddly enough. Basically, curl's digest pre-request doesn't include any body (the body of the upload) but wget's does. By not forcing the auth check early enough, the request falls through to the extractPackage call, which fails, falling through to a 404. Since this behavior isn't the same as browsers or wget, it only arose in this one transport type. We have a fix in the works.
