### ISSUE TITLE
Normalise package names

### ISSUE THREAD

**Issue by chessai** [haskell/hackage-server#781]
Hackage does not allow packages to be uploaded whose name matches that of an existing package modulo case. A frequent (albeit minour) pain point is the library `QuickCheck`. Capitalised letters in package names bother me, as they waste time to type, so I tried to upload a package named `quickcheck` which uses cabal's reexported-modules feature to just re-export all modules of `QuickCheck`. This does not work because of the restriction on package names. If this restriction exists, would it be possible to normalise package names, so that for example, https://hackage.haskell.org/package/quickcheck redirects to https://hackage.haskell.org/package/QuickCheck ?

**Comment by gbaz** [comment]
We can't do this in part because there are existing situations of case-clash that are prior to the policy change. So normalisation would cause confusion in such cases. Furthermore, in general, we _do_ allow case-clashing packages to be uploaded, but only when the uploader of an only-in-case-differing package is the one who does it. So, e.g., a QuickCheck maintainer could upload `quickcheck`. This is in part to allow migration of packages between capitalization conventions.

So, you might be able to prevail on the QuickCheck maintainers to migrate to `quickcheck` for their package, and _they_ could start to use the all lower convention.

**Comment by chessai** [comment]
Okay, thank you.
