### ISSUE TITLE
Upload packages to local hackage-server

### ISSUE THREAD

**Issue by ozzzzz** [haskell/hackage-server#849]
After [fiasko](https://github.com/haskell/hackage-server/issues/846) with full copy of hackage-server, we are tring another way. The idea is the following: run clean hackage-server, get the libraries from stackage LTS (for example, [LTS-13.6](https://www.stackage.org/lts-13.6)) and upload libraries only from that list with selected versions.

But there are some libraries, that could not be uploaded. Some of them we can fix manually, but some of them not. For example, [erf-2.0.0.0](http://hackage.haskell.org/package/erf) library could not be uploaded (we tried different hacks with the source of this library). Now we are uploading with pure curl. But we tried `cabal upload` too. Error from local hackage-server while uploading: `Invalid package: The 'cabal-version' field could not be properly parsed.`.

So the question: what is the normal way to get selected libraries from global hackage and upload to the local hackage-server?

**Comment by ozzzzz** [comment]
Ok, I got it. As I mentioned before, we have a trouble with mirroring. If it will be helpful, I can describe all errors that we got.

@gbaz Is there any way to get just `state` folder from current hackage-server? To download it and run hackage-server locally (of course, without credentials). I think that it is the easiest and fasters way to do local copy of hackage-server.

**Comment by gbaz** [comment]
Getting the state folder from current hackage-server is not a good way to run a mirror. The right way to do it is to run the mirror tool. If you describe specific errors, we can help with solving them.

**Comment by ozzzzz** [comment]
Ok, we will be appreciate your help.

1. So we started from docker-image for the hackager-server and hackage-mirror:
```
FROM haskell:8.4.4

RUN apt-get update && apt-get install libicu-dev -y

RUN git clone https://github.com/haskell/hackage-server.git

WORKDIR hackage-server

# update, build and init hackage-server
# TODO: add install after build and replace `cabal new-run` in other files by calling exe-files

RUN cabal new-update

RUN cabal new-build

RUN cabal new-run hackage-server init

EXPOSE 8080

RUN rm -f state/db/Tags/Alias/open.lock
```
If you are interested in another two Dockerfiles, I can post it too.
So we have two dockers with shared volume and shared network.

2. We started from standard configuration from [this](https://github.com/haskell/hackage-server#mirroring) description. This way has two problems:
  - Process is going really long time and synchronisation is slow. We waited 1 week and it did not finished.
  - It crashed sometimes, so we used the flag `--keep-going`.
  - It required huge amount of CPU resources and it we failed with running it in parallel mode. Because of huge resources docker contained was killed by the system (actually, pure process on server was killed too).
  - Every time when we were restarting mirroring server it starts from the beginning of the libraries list. It very big problem.

3. After that we found out instruction on [wiki](https://github.com/haskell/hackage-server/wiki#mirroring). The type of sources of target are different (`hackage2` and `local` instead of `secure` and `hackage2`). With this configuration we had:
  - More faster synchronisation.
  - Mush less CPU resources are used.
  - When restart it starts not from the beginning of the list (but the number of remaining packages was different every time, that's annoying).
  - It crashed on package ` hermes-1.3.4.3`:
```
mirroring hermes-1.3.4.3
Warning: Failed to download package hermes-1.3.4.3,
  HTTP error code 451, Unknown Error
  http://hackage.haskell.org/package/hermes-1.3.4.3/hermes.cabal
Abandoning this mirroring attempt.
Next try will be in 5 minutes, at 09:59 UTC
```
And it was the error that we could not went through. And other configurations with the type has the same result.

**Comment by gbaz** [comment]
Sorry I've been too busy to reply for the past few days. I keep meaning to test things myself to see if all the answers are sufficiently correct, and have not had the time. @mlongob also can advise.

I believe that if you mirror to local instead of hackage2, you don't get a datadir that you can actually run a hackage out of! You just get a "directory" mirror.

The high memory consumption should be a factor of the hackage server itself, at scale, requiring high memory. I.e. not the mirror process, but the server that is mirrored to.

I'm not sure why it was starting from scratch every run. Perhaps it is because you are running `init` whenever you start the server? (If I understand the docker config and how you run it correctly).

as far as `hermes` it is deliberately in the "memory hole" but the mirror software should be resilient enough to deal with it being missing. If it is not, then we need to patch the software to handle it.

If your goal is just to run a _package_ mirror of hackage server, as opposed to a "local hackage" (i.e. where your own packages are uploaded as well) then you can do so without this mirror tool at all, which is designed to enable a "full" local hackage mirror. One such tool, that mirrors the packages and info to a s3 bucket (so cabal can use it, despite the fact that it does not provide the hackage ui) is here: https://github.com/haskell-hvr/hackage-mirror-tool

Also note that you can direct the local hackage mirror to _only_ mirror the packages you are interested in by modifying the script, instead of having it mirror every version of every package.

**Comment by gbaz** [comment]
(i.e., to be clear and answer your original question on this ticket -- how to mirror only specified packages, just pass only those packages as arguments to the mirror tool! You can see this described in the command-line help for the tool: https://github.com/haskell/hackage-server/blob/c812ec1f6dd8fb4d997354c862f92bf2f050c75e/Distribution/Client/Mirror/CmdLine.hs#L120)

**Comment by ozzzzz** [comment]
I understood you. We need real local hackage, and the main purpose of it is to store not only public, but also our private packages. Thank you for [this](https://github.com/haskell/hackage-server/blob/c812ec1f6dd8fb4d997354c862f92bf2f050c75e/Distribution/Client/Mirror/CmdLine.hs#L120) link, we tried it.

And we have trouble again. Now with the library [erf](http://hackage.haskell.org/package/erf):
```
hackage-mirror servers.cfg erf-2.0.0.0
```
The log is the following:
```
No cached index available for target repo
1 packages to mirror.
mirroring erf-2.0.0.0
hackage-mirror: Failed to upload package erf-2.0.0.0,
  HTTP error code 400, Bad Request
  http://admin:...@hackage-server:8080/package/erf-2.0.0.0/erf-2.0.0.0.tar.gz
  The 'cabal-version' field could not be properly parsed.
```

After that library erf can be found on local hackage, but there is no `tar` archive available.

**Comment by gbaz** [comment]
Ah, so mirroring doesn't bypass the issue with `erf`. Well if you really need `erf`, I suppose the only solution is to either update the package's cabal file so it specifies a version field, and upload that updated package to your server, or comment out the following lines, which enforce the `version field` check on upload: https://github.com/haskell/hackage-server/blob/master/Distribution/Server/Packages/Unpack.hs#L204

**Comment by ozzzzz** [comment]
Thank you, @gbaz! [This](https://github.com/ozzzzz/hackage-server/commit/b945d869f34efdf5a027fc9c4473eadb38f531d9) edits solved our problem. If it will be helpful, I can add flag to the hackage-server to ignore revisions.
