### ISSUE TITLE
Allow non-maintainer uploads

### ISSUE THREAD

**Issue by locallycompact** [haskell/hackage-server#956]
Hi, I'd like to propose non-maintainer uploads be permitted on hackage.

It's reached the point for me where a huge part of my github activity is posting "could you please release the fix?" on haskell libraries which require a new release to work with the latest version of ghc or a core dependency. It's very tedious for all involved, and I believe that other package policies such as debian's allow non-maintainer uploads with a hyphenated version for this reason.

https://wiki.debian.org/NonMaintainerUpload

Since we already allow revision edits, I think this could also be a reasonable addition. It's a lot of added work when a package falls out of package sets due to a bug, generally requiring people to manually add the dependency through git. There are strict rules around debian's NMUs that we could abide as well.

**Comment by gbaz** [comment]
Hackage trustees do have a NMU policy. Because of the strict rules it is also pretty tedious, which I think is ok: https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md#3-source-changes-simple-patches

This repo is for tickets for improving the codebase of the server or reporting issues on the main instance of the server itself. A change in policy for trustees or others regarding package upload rights should be discussed elsewhere -- probably starting with a thread on the haskell discourse (https://discourse.haskell.org/) and moving from there to an appropriate official proposal venue. I imagine it would be quite controversial -- as it stands I feel our existing NMUs are enough, although more (and more proactive) trustees would expedite things when a big breaking change hits.

As such, I'm going to close this ticket to encourage further discussion (if warranted) in a broader venue.
